In [6]:
import numpy as np

path = "hw01_data/"

## Змейка m x n

Result: 2/2

![](hw02_images/img.png)

In [55]:
def snake(m, n):
    c = np.asarray(np.arange(1, n+1))
    return np.asarray([(c[-1] * i + c)[::-1] if i % 2 != 0 else c[-1] * i + c for i in range(m)])

In [56]:
print(snake(3, 4))

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


## Продукты

Result: 3/3

![](hw02_images/img_1.png)

In [99]:
def calculate(products, cook):
    temp = [int(x) for x in np.ceil((np.asarray(products).T*np.asarray(cook)).T.sum(axis=0))]
    print("Молоко, литры:", temp[0])
    print("Яйца, штуки:", temp[1])
    print("Мука, кг:", temp[-1])

In [100]:
products = np.array([
    [0.1, 2, 0.05],
    [0.2, 1, 0.2],
    [0.5, 3, 0.3]
])

cook = [10, 32, 8]

calculate(products, cook)

Молоко, литры: 12
Яйца, штуки: 76
Мука, кг: 10


## K ближайших пингвинов

Result: 15/15

![](hw02_images/img_2.png)

In [133]:
import pandas as pd
import numpy as np

n, k = int(input()), int(input())
data = pd.read_csv(path+"penguins.csv").dropna()
idk = pd.DataFrame({"bill_length_mm": data["bill_length_mm"], "bill_depth_mm": data["bill_depth_mm"]}).to_numpy()


def norm(x1, x2):
    return np.sqrt(((x1 - x2) ** 2).sum())


def find_k_neighbors(X, n, k):
    x0 = X[n]
    distances = {}
    for i in range(X.shape[0]):
        distances[i] = norm(X[i], x0)
    res = np.asarray([X[el[0]] for el in sorted(distances.items(), key=lambda item: item[1])[1:k + 1]])
    return res


print("\n".join([str(el) for el in find_k_neighbors(idk, n, k)]))

[40.5 17.9]
[40.3 18.5]
[39.7 17.9]
