In [1]:
import pandas as pd
import numpy as np
import sympy as sp
from autograd import grad

In [2]:
z = lambda v: 13*v[0]**3 - 7*v[0]*v[1] + v[1]**2 + 2*v[1]**3 - 97
start_point = np.array([1, 2], dtype=np.float64)
gamma = 0.1

In [3]:
grad(z)(start_point)

array([25., 21.])

In [4]:
start_point - gamma*grad(z)(start_point)

array([-1.5, -0.1])

In [5]:
second_point = start_point - gamma*grad(z)(start_point)
grad(z)(second_point)

array([88.45, 10.36])

In [6]:
second_point - gamma*grad(z)(second_point)

array([-10.345,  -1.136])

In [7]:
a = lambda x: 2*x + 3
w0 = 3
w1 = 2

# X = np.asarray([[3], [0], [2], [1]])
X = np.asarray([3, 0, 2, 1])
y = np.asarray([8, 3, 6, 5])
a(X)

array([9, 3, 7, 5])

# Градиентный спуск по неизвестной функции

Result: 100/100

![](hw04_images/img.png)

In [57]:
import numpy as np
from numpy.linalg import norm


def gradient(f, x0, dx=1e-9):
    return (f(x0 + dx) - f(x0)) / dx


def gradient_descent(func, start_point, gamma, epsilon, steps):
    x = [np.asarray([start_point], dtype=np.float64)]

    for i in range(steps):
        x.append(x[-1] - gamma * gradient(func, x[-1]))
    if len(x) > 1:
        return np.asarray(np.round(x, 3))

    x.append(x[-1] - gamma * gradient(func, x[-1]))
    while norm(func(x[-1]) - func(x[-2])) > epsilon:
        x.append(x[-1] - gamma * gradient(func, x[-1]))
    return np.asarray(np.round(x, 3))

In [58]:
def f(x):
    return np.sin(x) #x[0]**2+x[1]**2
start_point = 1
gamma = 0.1
epsilon = 1e-2
steps = 5

print(gradient_descent(f, start_point, gamma, epsilon, steps))

[[ 1.   ]
 [ 0.946]
 [ 0.887]
 [ 0.824]
 [ 0.756]
 [ 0.684]
 [ 0.606]
 [ 0.524]
 [ 0.437]
 [ 0.347]
 [ 0.253]
 [ 0.156]
 [ 0.057]
 [-0.043]
 [-0.143]
 [-0.242]
 [-0.339]
 [-0.433]
 [-0.524]
 [-0.61 ]
 [-0.692]
 [-0.769]
 [-0.841]
 [-0.908]
 [-0.969]
 [-1.026]
 [-1.078]
 [-1.125]
 [-1.168]
 [-1.207]
 [-1.243]
 [-1.275]]


In [59]:
def f_1(x: float) -> float:
    return (5 * x ** 6 + 24 * x ** 5 - 75 * x ** 4 + 135 * x ** 2 - 400 * x ** 3 + 1000 * x) / 100


print(gradient_descent(f_1, 2, .01, .1, 0))

[[2.   ]
 [2.278]
 [2.587]
 [2.854]
 [2.988]
 [3.008]]


In [ ]:
import numpy as np


def gradient_descent(func, start_point, gamma, epsilon, steps):
    delta_x = 1e-9
    history = [start_point]
    current = start_point
    prev_value = None
    current_value = func(current)

    if steps == 0:
        max_iter = 1000
        for _ in range(max_iter):
            gradient = (func(current + delta_x) - func(current - delta_x)) / (2 * delta_x)
            current = current - gamma * gradient
            current_value = func(current)
            history.append(np.round(current, 3))

            if prev_value is not None and abs(current_value - prev_value) < epsilon:
                break
            prev_value = current_value
    else:
        for _ in range(steps):
            gradient = (func(current + delta_x) - func(current)) / delta_x
            current = current - gamma * gradient
            history.append(np.round(current, 3))

    return np.array(history).reshape(-1, 1)